### ISSUE TITLE
Forwarder is not defined

### ISSUE THREAD

**Issue by six-days** [opengsn/metacoin#8]
```
npx truffle migrate                                                                                                                              1 ↵

Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.



Starting migrations...
======================
> Network name:    'development'
> Network id:      5777
> Block gas limit: 6721975 (0x6691b7)


1_initial_migration.js
======================
   -------------------------------------
   > Total cost:                   0 ETH
2_deploy_contracts.js
=====================

ReferenceError: Forwarder is not defined
    at deployFunc (/Users/go/src/six-days/blockchain/metacoin/migrations/2_deploy_contracts.js:11:42)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Migration._deploy (/Users/go/src/six-days/blockchain/metacoin/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:73:1)
    at Migration._load (/Users/go/src/six-days/blockchain/metacoin/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:55:1)
    at Migration.run (/Users/go/src/six-days/blockchain/metacoin/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:171:1)
    at Object.runMigrations (/Users/go/src/six-days/blockchain/metacoin/node_modules/truffle/build/webpack:/packages/migrate/index.js:150:1)
    at Object.runFrom (/Users/go/src/six-days/blockchain/metacoin/node_modules/truffle/build/webpack:/packages/migrate/index.js:110:1)
    at Object.run (/Users/go/src/six-days/blockchain/metacoin/node_modules/truffle/build/webpack:/packages/migrate/index.js:87:1)
    at runMigrations (/Users/go/src/six-days/blockchain/metacoin/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate.js:269:1)
    at /Users/go/src/six-days/blockchain/metacoin/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate.js:231:1
Truffle v5.1.43 (core: 5.1.43)
Node v12.18.3

```

the file https://github.com/opengsn/metacoin/blob/master/migrations/2_deploy_contracts.js
note define Forwarder

**Comment by naiba** [comment]
```
npm i -g truffle
truffle compile --all
```
